build_wilson:
	docker build -t telegram-wilson . 

run_wilson:
	docker run -it -d --name telegram-wilson telegram-wilson 

start_wilson:
	docker start telegram-wilson

stop_wilson:
	docker stop telegram-wilson
